// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topic: typeof import('./src/components/topic/Topic.vue')['default']
    TopicCommon: typeof import('./src/components/topic/TopicCommon.vue')['default']
    TopicMultiple: typeof import('./src/components/topic/TopicMultiple.vue')['default']
    TopicRadio: typeof import('./src/components/topic/TopicRadio.vue')['default']
  }
}
