// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Answer: typeof import('./src/components/topic/Answer.vue')['default']
    Chapter: typeof import('./src/components/topic/Chapter.vue')['default']
    FilterQuestions: typeof import('./src/components/topic/FilterQuestions.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Logs: typeof import('./src/components/Logs.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topic: typeof import('./src/components/topic/Topic.vue')['default']
    TopicAnswerQuestion: typeof import('./src/components/topic/TopicAnswerQuestion.vue')['default']
    TopicCommon: typeof import('./src/components/topic/TopicCommon.vue')['default']
    TopicInput: typeof import('./src/components/topic/TopicInput.vue')['default']
    TopicMultiple: typeof import('./src/components/topic/TopicMultiple.vue')['default']
    TopicRadio: typeof import('./src/components/topic/TopicRadio.vue')['default']
    TopicTrueOrFalse: typeof import('./src/components/topic/TopicTrueOrFalse.vue')['default']
    UpdateLog: typeof import('./src/components/topic/UpdateLog.vue')['default']
  }
}
